import { useState } from 'react';
import { ArrowDown, ArrowUp, ArrowUpRight, ChevronDown, Download, Filter, Mail, MoreHorizontal, Package, Plus, Search, SlidersHorizontal, UserPlus } from 'lucide-react';

type View = 'orders' | 'customers' | 'inventory' | 'analytics' | 'settings';

const orderRows = [
  ['#ORD-1048','Olivia Martin','Workspace Pro','Jul 4, 2026','$1,280.00','Completed'],
  ['#ORD-1047','Jackson Lee','Ergo Chair','Jul 4, 2026','$860.00','Processing'],
  ['#ORD-1046','Sophia Brown','Studio Lamp','Jul 3, 2026','$320.00','Completed'],
  ['#ORD-1045','Noah Williams','Desk Organizer','Jul 3, 2026','$145.00','Pending'],
  ['#ORD-1044','Emma Davis','Monitor Stand','Jul 2, 2026','$490.00','Completed'],
  ['#ORD-1043','Liam Wilson','Task Chair','Jul 2, 2026','$710.00','Cancelled'],
  ['#ORD-1042','Ava Anderson','Oak Desk','Jul 1, 2026','$1,620.00','Processing'],
];
const customers = [
  ['OM','Olivia Martin','olivia@acme.co','Acme Inc.','12','$8,420','Active'],
  ['JL','Jackson Lee','jackson@north.io','North Labs','8','$5,160','Active'],
  ['SB','Sophia Brown','sophia@studio.co','Studio & Co.','15','$11,890','Active'],
  ['NW','Noah Williams','noah@bright.in','Brightworks','4','$2,310','Inactive'],
  ['ED','Emma Davis','emma@field.com','Field House','7','$4,980','Active'],
];
const products = [
  ['Workspace Pro','OFF-1001','Office Furniture','126','34','$1,280','Healthy'],
  ['Ergo Chair','OFF-1002','Office Furniture','42','18','$430','Low stock'],
  ['Studio Lamp','LGT-2041','Lighting','8','24','$160','Low stock'],
  ['Oak Desk','OFF-1014','Office Furniture','0','10','$810','Out of stock'],
  ['Monitor Stand','ACC-3205','Accessories','84','20','$245','Healthy'],
  ['Desk Organizer','ACC-3210','Accessories','163','30','$72','Healthy'],
];

function PageHeader({ title, subtitle, action, actionIcon = <Plus size={17}/> }: { title:string; subtitle:string; action:string; actionIcon?:React.ReactNode }) {
  return <div className="workspace-heading"><div><p className="breadcrumb">Northstar / {title}</p><h1>{title}</h1><p>{subtitle}</p></div><button className="primary-button" onClick={() => alert(`${action} flow is ready to connect.`)}>{actionIcon}{action}</button></div>;
}
function Toolbar({ placeholder }: { placeholder:string }) {
  return <div className="data-toolbar"><div className="inline-search"><Search size={16}/><input placeholder={placeholder}/></div><button><Filter size={15}/> Filter</button><button><SlidersHorizontal size={15}/> Columns</button><button className="export"><Download size={15}/> Export</button></div>;
}
function Status({ children }: { children:string }) { return <span className={`status ${children.toLowerCase().replaceAll(' ','-')}`}>{children}</span>; }

function OrdersPage() {
  const [tab,setTab]=useState('All orders');
  return <><PageHeader title="Sales orders" subtitle="Create, track, and fulfil customer orders." action="New sales order"/><div className="mini-metrics">
    <div><span>Orders this month</span><strong>1,284</strong><small className="positive"><ArrowUp size={12}/> 8.2%</small></div><div><span>Awaiting fulfilment</span><strong>46</strong><small>12 due today</small></div><div><span>Order value</span><strong>$48,290</strong><small className="positive"><ArrowUp size={12}/> 12.5%</small></div><div><span>Returns</span><strong>18</strong><small className="negative"><ArrowDown size={12}/> 2.4%</small></div>
  </div><section className="panel data-panel"><div className="data-tabs">{['All orders','Pending','Processing','Completed'].map(x=><button key={x} className={tab===x?'active':''} onClick={()=>setTab(x)}>{x}</button>)}</div><Toolbar placeholder="Search sales orders..."/><div className="table-scroll"><table><thead><tr><th>Order</th><th>Customer</th><th>Product</th><th>Order date</th><th>Amount</th><th>Status</th><th></th></tr></thead><tbody>{orderRows.filter(r=>tab==='All orders'||r[5]===tab).map(r=><tr key={r[0]}>{r.slice(0,5).map((c,i)=><td key={c}>{i===0||i===4?<strong>{c}</strong>:c}</td>)}<td><Status>{r[5]}</Status></td><td><MoreHorizontal size={17}/></td></tr>)}</tbody></table></div><Pager count="1–7 of 1,284"/></section></>;
}
function CustomersPage(){return <><PageHeader title="Customers" subtitle="Manage customer details and account activity." action="Add customer" actionIcon={<UserPlus size={17}/>}/><div className="mini-metrics three"><div><span>Total customers</span><strong>3,842</strong><small className="positive"><ArrowUp size={12}/> 4.6% this month</small></div><div><span>Active customers</span><strong>3,216</strong><small>83.7% of total</small></div><div><span>Average customer value</span><strong>$1,264</strong><small className="positive"><ArrowUp size={12}/> $84 this month</small></div></div><section className="panel data-panel"><Toolbar placeholder="Search name, email or company..."/><div className="table-scroll"><table><thead><tr><th>Customer</th><th>Email</th><th>Company</th><th>Orders</th><th>Total spent</th><th>Status</th><th></th></tr></thead><tbody>{customers.map(r=><tr key={r[1]}><td><div className="customer"><span className="avatar lilac">{r[0]}</span><strong>{r[1]}</strong></div></td><td><span className="mail-cell"><Mail size={13}/>{r[2]}</span></td>{r.slice(3,6).map((c,i)=><td key={c}>{i===2?<strong>{c}</strong>:c}</td>)}<td><Status>{r[6]}</Status></td><td><MoreHorizontal size={17}/></td></tr>)}</tbody></table></div><Pager count="1–5 of 3,842"/></section></>}
function InventoryPage(){return <><PageHeader title="Inventory" subtitle="Monitor stock levels, products, and reorder points." action="Add item"/><div className="inventory-alert"><div><Package/><span><strong>18 products need your attention</strong><small>10 are low in stock and 8 are currently unavailable.</small></span></div><button>Review items <ArrowUpRight size={15}/></button></div><div className="mini-metrics"><div><span>Total stock value</span><strong>$184,650</strong><small>Across 1,842 items</small></div><div><span>Items in stock</span><strong>1,402</strong><small className="positive">76% healthy stock</small></div><div><span>Low stock</span><strong>312</strong><small className="warning">17% need reorder</small></div><div><span>Out of stock</span><strong>128</strong><small className="negative">7% unavailable</small></div></div><section className="panel data-panel"><Toolbar placeholder="Search products or SKU..."/><div className="table-scroll"><table><thead><tr><th>Item name</th><th>SKU</th><th>Category</th><th>Available</th><th>Reorder at</th><th>Unit price</th><th>Stock status</th></tr></thead><tbody>{products.map(r=><tr key={r[1]}>{r.slice(0,6).map((c,i)=><td key={c}>{i===0?<strong>{c}</strong>:c}</td>)}<td><Status>{r[6]}</Status></td></tr>)}</tbody></table></div><Pager count="1–6 of 1,842"/></section></>}
function AnalyticsPage(){return <><PageHeader title="Analytics" subtitle="Understand performance across your entire business." action="Export report" actionIcon={<Download size={17}/>}/><div className="report-filter"><span>Business overview</span><button>Jul 1 – Jul 31, 2026 <ChevronDown size={14}/></button></div><div className="mini-metrics"><div><span>Gross revenue</span><strong>$64,820</strong><small className="positive"><ArrowUp size={12}/> 14.2%</small></div><div><span>Net profit</span><strong>$21,430</strong><small className="positive"><ArrowUp size={12}/> 9.8%</small></div><div><span>Expenses</span><strong>$18,270</strong><small className="negative"><ArrowUp size={12}/> 3.1%</small></div><div><span>Profit margin</span><strong>33.1%</strong><small className="positive"><ArrowUp size={12}/> 1.8%</small></div></div><div className="report-grid"><section className="panel report-chart"><div className="panel-heading"><div><h2>Revenue and expenses</h2><p>Monthly financial performance</p></div><span className="legend"><i/> Revenue <i/> Expenses</span></div><div className="bar-chart">{[42,55,48,68,62,80,72,91,84,76,94,88].map((h,i)=><div key={i}><i style={{height:`${h}%`}}/><i style={{height:`${h*.52}%`}}/><span>{['Aug','Sep','Oct','Nov','Dec','Jan','Feb','Mar','Apr','May','Jun','Jul'][i]}</span></div>)}</div></section><section className="panel top-products"><div className="panel-heading"><div><h2>Top products</h2><p>By revenue this month</p></div></div>{[['Workspace Pro','$18,420','38%'],['Oak Desk','$11,680','24%'],['Ergo Chair','$8,940','18%'],['Monitor Stand','$5,120','11%']].map((p,i)=><div className="rank-row" key={p[0]}><b>{i+1}</b><span>{p[0]}<small>{p[2]} of revenue</small></span><strong>{p[1]}</strong></div>)}</section></div></>}
function SettingsPage(){const [saved,setSaved]=useState(false);return <><PageHeader title="Settings" subtitle="Manage your organization and workspace preferences." action="Save changes" actionIcon={null}/><div className="settings-layout"><aside className="settings-nav">{['Organization','Users & roles','Sales & taxes','Inventory','Notifications','Integrations'].map((x,i)=><button className={i===0?'active':''} key={x}>{x}</button>)}</aside><section className="panel settings-form"><div className="settings-title"><h2>Organization profile</h2><p>This information appears on documents and customer emails.</p></div><div className="logo-upload"><div>N</div><span><strong>Organization logo</strong><small>PNG, JPG or SVG. Maximum 2 MB.</small><button>Change logo</button></span></div><div className="form-grid"><label>Organization name<input defaultValue="Northstar Workspace"/></label><label>Business type<select defaultValue="Retail"><option>Retail</option><option>Services</option><option>Manufacturing</option></select></label><label>Business email<input defaultValue="hello@northstar.co"/></label><label>Phone number<input defaultValue="+91 98765 43210"/></label><label className="full">Business address<input defaultValue="14 Residency Road, Bengaluru, Karnataka 560025"/></label><label>Base currency<select defaultValue="USD"><option>USD — US Dollar</option><option>INR — Indian Rupee</option></select></label><label>Fiscal year<select><option>April – March</option><option>January – December</option></select></label></div><div className="settings-actions"><button onClick={()=>setSaved(true)}>Save changes</button>{saved&&<span>Changes saved successfully.</span>}</div></section></div></>}
function Pager({count}:{count:string}){return <div className="pager"><span>Showing {count}</span><div><button disabled>Previous</button><button>Next</button></div></div>}
export default function BusinessPage({view}:{view:View}){return <div className="business-page">{view==='orders'?<OrdersPage/>:view==='customers'?<CustomersPage/>:view==='inventory'?<InventoryPage/>:view==='analytics'?<AnalyticsPage/>:<SettingsPage/>}</div>}
